<script setup>
import { computed } from 'vue';
import { RouterLink } from 'vue-router';
import { ArrowRight, BookOpen, Flame, Gauge, Star, Target, Trophy } from '@lucide/vue';
import { levels, lessons, lessonTitle, profile } from '../stores/profile';

const currentLevel = computed(() => levels.find((item) => profile.totalXp < item.max) ?? levels.at(-1));
const nextLevel = computed(() => levels[levels.indexOf(currentLevel.value) + 1]);
const completed = computed(() => lessons.filter((item) => profile.completedLessons.includes(profile.system === 'BISINDO' ? `bisindo-${item.id}` : item.id)));
const nextLesson = computed(() => lessons.find((item) => !profile.completedLessons.includes(profile.system === 'BISINDO' ? `bisindo-${item.id}` : item.id)));
const week = computed(() => Array.from({ length: 7 }, (_, index) => { const date = new Date(); date.setHours(0,0,0,0); date.setDate(date.getDate() - (6-index)); const key = `${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,'0')}-${String(date.getDate()).padStart(2,'0')}`; return { label: ['Min','Sen','Sel','Rab','Kam','Jum','Sab'][date.getDay()], count: profile.activityByDate[key] ?? 0, today: index === 6 }; }));
const maxCount = computed(() => Math.max(1, ...week.value.map((day) => day.count)));
</script>

<template>
    <div class="progress-page"><section class="progress-hero"><div><span class="eyebrow mint-eyebrow">RINGKASAN BELAJAR · {{ profile.system }}</span><h1>Kamu sedang<br/><span>bertumbuh hebat.</span></h1><p>Setiap latihan menambah cara baru untuk terhubung.</p><div class="progress-hero-level"><span class="level-star">✦</span><div><b>{{ currentLevel.name }}</b><small>{{ nextLevel ? `${nextLevel.min-profile.totalXp} XP menuju ${nextLevel.name}` : 'Level tertinggi!' }}</small></div><strong>{{ profile.totalXp-currentLevel.min }}<small> / {{ nextLevel ? nextLevel.min-currentLevel.min : 100 }} XP</small></strong></div><div class="level-track"><i :style="{ width: `${nextLevel ? (profile.totalXp-currentLevel.min)/(nextLevel.min-currentLevel.min)*100 : 100}%` }"></i></div></div><div class="course-donut" :style="{ background: `conic-gradient(#31a982 ${completed.length/lessons.length*100}%, #e7eee8 0)` }"><div><b>{{ Math.round(completed.length/lessons.length*100) }}<small>%</small></b><span>jalur selesai</span></div></div></section>
        <section class="progress-stat-grid"><article class="progress-stat-card card xp"><span class="stat-icon"><Star :size="18"/></span><small>XP TERKUMPUL</small><b>{{ profile.totalXp }}</b><span class="stat-caption">Dari aktivitas belajarmu</span></article><article class="progress-stat-card card lessons"><span class="stat-icon"><BookOpen :size="18"/></span><small>LESSON SELESAI</small><b>{{ completed.length }}<i>/{{ lessons.length }}</i></b><span class="stat-caption">Terus buka jalur baru</span></article><article class="progress-stat-card card streak"><span class="stat-icon"><Flame :size="18"/></span><small>STREAK SAAT INI</small><b>{{ profile.currentStreak }}<i> hari</i></b><span class="stat-caption">Terpanjang: {{ profile.longestStreak }} hari</span></article><article class="progress-stat-card card accuracy"><span class="stat-icon"><Gauge :size="18"/></span><small>LATIHAN GESTURE</small><b>{{ profile.completedPractices.length }}</b><span class="stat-caption">Huruf unik yang dicoba</span></article></section>
        <div class="progress-detail-grid"><section class="activity-card card"><div class="section-title-row"><div><span class="eyebrow">RITME MINGGU INI</span><h2>Aktivitas belajarmu</h2><p>{{ week.reduce((sum,day)=>sum+day.count,0) }} sesi tercatat dalam 7 hari</p></div><span class="activity-bubble">📅</span></div><div class="activity-bars"><div v-for="(day,index) in week" :key="`${day.label}-${index}`" class="activity-day" :class="{today:day.today}"><div class="activity-bar-back"><i :style="{height:day.count ? `${Math.max(14,day.count/maxCount*100)}%` : '0%'}"></i></div><small>{{ day.label }}</small><span v-if="day.today" class="today-label">HARI INI</span></div></div><div class="activity-foot"><span><i></i> Aktivitas lesson dan practice</span><small>Data tersimpan lokal</small></div></section>
            <section class="consistency-card card"><span class="eyebrow">TARGET HARIAN</span><div class="consistency-icon">🎯</div><h2>{{ profile.challengeClaimed ? 'Tantangan selesai!' : 'Praktikkan 5 gesture' }}</h2><p>{{ profile.challengeClaimed ? 'Kamu sudah mengklaim hadiah hari ini.' : 'Coba huruf baru melalui sesi AI Practice.' }}</p><div class="challenge-meter-label"><b>{{ profile.challengeProgress }} / 5</b><span>gesture</span></div><div class="progress-track"><i :style="{width:`${profile.challengeProgress*20}%`}"></i></div><div class="consistency-reward"><span>Hadiah tantangan</span><b>⭐ +20 XP</b></div><RouterLink to="/challenge" class="consistency-link">Lihat tantangan <ArrowRight :size="15"/></RouterLink></section></div>
        <section class="progress-path-card card"><div class="section-title-row"><div><span class="eyebrow">LANJUTKAN PERJALANAN</span><h2>Jalur {{ profile.system }}</h2><p>{{ completed.length }} dari {{ lessons.length }} lesson selesai.</p></div><RouterLink to="/learn" class="path-all-link">Lihat semua <ArrowRight :size="15"/></RouterLink></div><div class="mini-path-list"><div v-for="(lesson,index) in lessons.slice(0,4)" :key="lesson.id" class="mini-path-item" :class="{complete:completed.includes(lesson),next:nextLesson?.id===lesson.id}"><span class="mini-path-node">{{ completed.includes(lesson) ? '✓' : index+1 }}</span><div><b>{{ lessonTitle(lesson) }}</b><small>{{ completed.includes(lesson) ? 'Selesai' : nextLesson?.id===lesson.id ? 'Lesson berikutnya' : 'Terkunci' }}</small></div><span class="mini-path-xp">{{ completed.includes(lesson) ? '✓' : '+10 XP' }}</span></div></div><RouterLink v-if="nextLesson" :to="`/lesson/${profile.system === 'BISINDO' ? 'bisindo-' : ''}${nextLesson.id}`" class="primary-button progress-continue">Lanjutkan lesson <ArrowRight :size="17"/></RouterLink><div v-else class="course-complete"><Trophy :size="17"/> Semua lesson selesai!</div></section>
        <div class="progress-note"><Target :size="15"/> Aktivitas, XP, dan progres disimpan lokal untuk demo.</div>
    </div>
</template>
