'use client';
import { useState } from 'react';
import Link from 'next/link';
import { ArrowRight, CircleCheck, Pencil, RotateCcw, Save, Sparkles, Target, X } from 'lucide-react';
import { TopStats } from '@/components/layout/TopStats';
import { useDemo } from '@/components/providers/DemoProvider';
import { levels } from '@/data/gamification';
import { lessonsBySystem } from '@/data/lessons';

export function InfoPage({ kind }: { kind: 'challenge' | 'profile' }) {
  const { profile, finishChallenge, reset, setDisplayName } = useDemo();
  const [editingName, setEditingName] = useState(false);
  const [nameDraft, setNameDraft] = useState(profile.displayName);
  const lessons = lessonsBySystem[profile.system];
  const completed = profile.completedLessons.filter(id => lessons.some(lesson => lesson.id === id));
  const level = levels.find(item => profile.totalXp < item.max) ?? levels[levels.length - 1];
  return <><TopStats/><div className="info-page"><div className="eyebrow mint-eyebrow">SIGNTEACH · DEMO</div><h1>{kind === 'challenge' ? 'Daily Challenge' : 'Profil Pelajar'}</h1><p className="info-lead">{kind === 'challenge' ? 'Selesaikan target latihan untuk mendapatkan XP bonus.' : 'Ruang personal untuk perjalanan belajarmu.'}</p>
    {kind === 'challenge' && <div className="challenge-large card"><div className="challenge-hero"><span className="challenge-big-icon">🎯</span><div><span className="eyebrow">TANTANGAN HARIAN</span><h2>Praktikkan 5 gesture</h2><p>Selesaikan lesson dan praktikkan gesture untuk mengisi target ini.</p></div></div><div className="challenge-progress-label"><b>{profile.challengeProgress} dari 5 gesture</b><span>{profile.challengeProgress >= 5 ? 'Tuntas!' : `Kurang ${5 - profile.challengeProgress} lagi`}</span></div><div className="progress-track big-track"><i style={{ width: `${profile.challengeProgress * 20}%` }}/></div><div className="challenge-reward">🎁 Hadiah saat tantangan selesai <b>+20 XP</b></div>{profile.challengeClaimed ? <div className="claimed-note"><CircleCheck size={18}/> Hadiah +20 XP sudah diklaim.</div> : profile.challengeProgress >= 5 ? <button className="primary-button" onClick={finishChallenge}>KLAIM +20 XP <ArrowRight size={18}/></button> : <Link className="primary-button challenge-continue" href="/learn">LANJUTKAN BELAJAR <ArrowRight size={18}/></Link>}<p className="demo-caption">Progress bertambah setelah lesson dan praktik gesture selesai.</p></div>}
    {kind === 'profile' && <div className="profile-card card"><div className="profile-hero"><div className="profile-avatar">{profile.displayName.trim().charAt(0).toUpperCase() || 'A'}</div><div className="profile-identity"><span className="eyebrow">PELAJAR SIGNTEACH</span>{editingName ? <form className="name-edit-form" onSubmit={event => { event.preventDefault(); setDisplayName(nameDraft); setEditingName(false); }}><label className="sr-only" htmlFor="display-name">Nama profil</label><input id="display-name" autoFocus maxLength={32} value={nameDraft} onChange={event => setNameDraft(event.target.value)}/><button type="submit" aria-label="Simpan nama"><Save size={16}/></button><button type="button" aria-label="Batal mengedit nama" onClick={() => { setNameDraft(profile.displayName); setEditingName(false); }}><X size={16}/></button></form> : <><h2>{profile.displayName}</h2><button className="edit-name" onClick={() => setEditingName(true)}><Pencil size={13}/> Edit nama</button></>}<span>Student · Bergabung September 2026</span></div></div><div className="profile-fields"><div><span>Sistem belajar</span><b>{profile.system}</b></div><div><span>Level</span><b>{level.name}</b></div><div><span>Total XP</span><b>{profile.totalXp} XP</b></div><div><span>Lesson selesai</span><b>{completed.length} lesson</b></div><div><span>Streak terpanjang</span><b>{profile.longestStreak} hari</b></div><div><span>Gesture dipraktikkan</span><b>{profile.completedPractices.length} gesture</b></div></div><Link href="/learn" className="secondary-link">Lanjut belajar <ArrowRight size={16}/></Link><div className="profile-challenge-short"><Target size={16}/><span>Daily Challenge</span><b>{profile.challengeProgress}/5</b><Link href="/challenge" aria-label="Lihat Daily Challenge"><ArrowRight size={15}/></Link></div><div className="reset-area"><button className="text-button" onClick={() => { if (confirm('Reset semua progress demo di perangkat ini?')) reset(); }}><RotateCcw size={15}/> Reset progress demo</button><small>Data demo tersimpan lokal di browser.</small></div></div>}
    <footer className="info-footnote"><Sparkles size={16}/> SignTeach · Setiap tanda membuka cerita baru.</footer>
  </div></>;
}
